package org.DATA.ApacheDerby;

import java.sql.*;

public class ApacheDerby {

    static final String DB_URL = "jdbc:derby://localhost/1527/chatDB:create=true";

    static final String TABLE_USER = "CREATE TABLE User (" +
            "userID (INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1))" +
            "fio (VARCHAR 255)" +
            "post (VARCHAR 255)" +
            "login (VARCHAR 255)" +
            "password (VARCHAR 255)";

    static final String TABLE_HISTORY = "CREATE TABLE History (" +
            "messageID (INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1))" +
            "dateNessage (TIMESTAMP)" +
            "userMessage CONSTRAINT user_fk FOREIGN KEY (userID) REFERENCES User(userID)" +
            "typeMessage (VARCHAR 2)" +
            "message (VARCHAR 3000))";

    public static void dataBaseCreate() {
        try {
            Connection connection = DriverManager.getConnection(DB_URL);
            Statement statement = connection.createStatement();

            System.out.println("Создаем таблицу");
            statement.execute(TABLE_USER);
            System.out.println("Таблица " + TABLE_USER.trim() + " создана");
            statement.execute(TABLE_HISTORY);
            System.out.println("Таблица " + TABLE_HISTORY.trim() + " создана");
            statement.close();
            connection.close();
            System.out.println("База данных создана");


        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }

    public static void connectDataBase() {
        String url = "jdbc:derby://localhost:1527/chatDB";

        try {
            Connection connection = DriverManager.getConnection(url);
            PreparedStatement statement = connection.prepareStatement("SELECT * FROM TABLE_USER");
            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                String id = resultSet.getString("userID");
                String fio = resultSet.getString("fio");
                String post = resultSet.getString("post");
                String login = resultSet.getString("login");
                String password = resultSet.getString("password");
                System.out.println("ID: " + id);
                System.out.println("ФИО: " + fio);
                System.out.println("Должность: " + post);
                System.out.println("Логин: " + login);
                System.out.println("Пароль: " + password);
            }
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        System.out.println("Подключение выполнено");

    }

    public static void main(String[] args) {
        if (!true) {
            connectDataBase();
        }
        else {
            dataBaseCreate();
        }
    }
}
