package org.DATA.ApacheDerby;

import java.sql.*;

import static java.lang.Class.forName;


public class ApacheDerby {

    private static final String DB_URL = "jdbc:derby:Database/chatDB";

    private static final String DB_URL_MODIFY = ":create=true";

    private static final String DRIVER = "org.apache.derby.jdbc.EmbeddedDriver";

    static final String TABLE_USER = "CREATE TABLE User (" +
            "userID (INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1))" +
            "fio (VARCHAR 255)" +
            "post (VARCHAR 255)" +
            "login (VARCHAR 255)" +
            "password (VARCHAR 255)";

    static final String TABLE_HISTORY = "CREATE TABLE History (" +
            "messageID (INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1))" +
            "dateNessage (TIMESTAMP)" +
            "userMessage CONSTRAINT user_fk FOREIGN KEY (userID) REFERENCES User(userID)" +
            "typeMessage (VARCHAR 2)" +
            "message (VARCHAR 3000))";

    private static String dbName = null;

    private static Connection connection = null;

    public static void createDataBase() {
        try {
            Class.forName(DRIVER);
            Connection connection = DriverManager.getConnection(DB_URL + DB_URL_MODIFY);
            Statement statement = connection.createStatement();

            System.out.println("Создаем таблицу");
            statement.execute(TABLE_USER);
            System.out.println("Таблица " + TABLE_USER.trim() + " создана");
            statement.execute(TABLE_HISTORY);
            System.out.println("Таблица " + TABLE_HISTORY.trim() + " создана");
            statement.close();
            connection.close();
            System.out.println("База данных создана");


        } catch (Exception throwables) {
            throwables.printStackTrace();
        }
    }

    public static void connectDataBase() {
        try {
            Class.forName(DRIVER);
            Connection connection = DriverManager.getConnection(DB_URL);
         /*   PreparedStatement statement = connection.prepareStatement("SELECT * FROM TABLE_USER");
            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                String id = resultSet.getString("userID");
                String fio = resultSet.getString("fio");
                String post = resultSet.getString("post");
                String login = resultSet.getString("login");
                String password = resultSet.getString("password");
                System.out.println("ID: " + id);
                System.out.println("ФИО: " + fio);
                System.out.println("Должность: " + post);
                System.out.println("Логин: " + login);
                System.out.println("Пароль: " + password);
            }*/
        } catch (Exception throwables) {
            throwables.printStackTrace();
        }
        System.out.println("Подключение выполнено");

    }

    public static void addRecordToTable() {                // Метод добавления записи в таблицу TABLE_HISTORY

    }

    public static void transferRecordInDuplicatedTable() { // Метод перемещения записи из таблицы TABLE_HISTORY в ее дубликат TABLE_HISTORY_DUPLICATED

    }

    public static void deleteRecordFromTable() {           // Метод удаления записи в таблице TABLE_HISTORY

    }

    public static void createUserToTable() {              // Метод создание пользователя в таблице TABLE_USER
        String query = "INSERT INTO TABLE_USER (userID, fio, post, login, password) VALUES (1, Админ, Администратор, admin, 123)";
    }

    public static void transferUserInDuplicatedTable() { // Метод перемещения пользователя из таблицы TABLE_USER в ее дубликат TABLE_USER_DUPLICATED

    }

    public static void deleteUserFromTable() {          // Метод удаления пользователя из таблицы TABLE_USER

    }

    public static boolean findDataBase() {              // Метод поиска базы данных (возвращает true если нашел)
        return true;
    }

    public static void main(String[] args) {
        if (findDataBase()) {               //Проверяем, если база данных есть, то подключаемся к ней, если нет, то создаем новую
            connectDataBase();
        } else {
            createDataBase();
        }
    }
}
